apiVersion: v1
kind: Secret
metadata:
  name: baklava-ai-secret
  labels:
    app: baklava-ai
type: Opaque
stringData:
  secret-key: "REPLACE_WITH_RANDOM_SECRET"
  oauth-client-id: "baklava-ai"
  oauth-client-secret: "REPLACE_WITH_OAUTH_CLIENT_SECRET"
